apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-heartbeat-with-lease
spec:
  delay:
    durationMilliseconds: 600000
    jitterDurationMilliseconds: 610000
  next:
    statusTemplate: |
      {{`{{ $now := Now }}
      {{ $lastTransitionTime := or .metadata.creationTimestamp $now }}
      conditions:
      {{ range NodeConditions }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ .message | Quote }}
        reason: {{ .reason | Quote }}
        status: {{ .status | Quote }}
        type: {{ .type | Quote }}
      {{ end }}

      addresses:
      {{ with .status.addresses }}
      {{ YAML . 1 }}
      {{ else }}
      {{ with NodeIP }}
      - address: {{ . | Quote }}
        type: InternalIP
      {{ end }}
      {{ with NodeName }}
      - address: {{ . | Quote }}
        type: Hostname
      {{ end }}
      {{ end }}

      {{ with NodePort }}
      daemonEndpoints:
        kubeletEndpoint:
          Port: {{ . }}
      {{ end }}`}}
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: .status.phase
      operator: In
      values:
      - Running
    - key: .status.conditions.[] | select( .type == "Ready" ) | .status
      operator: In
      values:
      - "True"
---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: node-initialize
spec:
  next:
    statusTemplate: |
      {{ .Files.Get "resources/node-initialize" | nindent 6 }}
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: .status.conditions.[] | select( .type == "Ready" ) | .status
      operator: NotIn
      values:
      - "True"
---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  next:
    statusTemplate: |
      {{ .Files.Get "resources/pod-complete" | nindent 6 }}
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: DoesNotExist
    - key: .status.phase
      operator: In
      values:
      - Running
    - key: .metadata.ownerReferences.[].kind
      operator: In
      values:
      - Job
---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-delete
spec:
  next:
    delete: true
    finalizers:
      empty: true
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: Exists
---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-ready
spec:
  next:
    statusTemplate: |
      {{ .Files.Get "resources/pod-ready" | nindent 6 }}
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: .metadata.deletionTimestamp
      operator: DoesNotExist
    - key: .status.podIP
      operator: DoesNotExist
