image:
  # -- Image pull policy.
  pullPolicy: IfNotPresent
  # -- Image repository.
  repository: registry.k8s.io/kwok/operator
  # -- Overrides the image tag whose default is {{ .Chart.AppVersion }}.
  tag: ""

# -- Image pull secrets.
imagePullSecrets: []

# -- Override the `name` of the chart.
nameOverride: ""

# -- Override the `fullname` of the chart.
fullnameOverride: "kwok-operator"

podSecurityContext: {}
securityContext: {}

nodeSelector: {}
resources: {}
affinity: {}

# -- The replica count for Deployment.
replicas: 1
