name: Bump Releases

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update
        run: |
          ./hack/supported_releases.sh
