apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kwok.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kwok.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kwok.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kwok.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
          - --manage-all-nodes=false
          - --manage-nodes-with-annotation-selector=kwok.x-k8s.io/node=fake
          - --manage-nodes-with-label-selector=
          - --manage-single-node=
          - --disregard-status-with-annotation-selector=kwok.x-k8s.io/status=custom
          - --disregard-status-with-label-selector=
          - --node-ip=$(POD_IP)
          - --node-port=10247
          - --cidr=10.0.0.1/24
          - --node-lease-duration-seconds=40
          - --enable-crds=Stage
          - --enable-crds=Metric
          - --enable-crds=Attach
          - --enable-crds=ClusterAttach
          - --enable-crds=Exec
          - --enable-crds=ClusterExec
          - --enable-crds=Logs
          - --enable-crds=ClusterLogs
          - --enable-crds=PortForward
          - --enable-crds=ClusterPortForward
          - --enable-crds=ResourceUsage
          - --enable-crds=ClusterResourceUsage
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: 10247
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: 10247
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 20
            timeoutSeconds: 2
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10247
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
