apiVersion: v1
kind: Service
metadata:
  name: {{ include "kwok.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kwok.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 10247
    protocol: TCP
    targetPort: 10247
  selector:
    {{- include "kwok.selectorLabels" . | nindent 4 }}
  type: ClusterIP
