apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-container-completed
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Running'
    - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
      operator: 'In'
      values:
      - 'True'
    - key: '.metadata.ownerReferences.[].kind'
      operator: 'In'
      values:
      - 'Job'
  weight: 1
  delay:
    durationMilliseconds: 1000
    jitterDurationMilliseconds: 5000
  next:
    delete: false
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      containerStatuses:
      {{ range $index, $item := .spec.containers }}
      {{ $origin := index $root.status.containerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: true
        restartCount: {{ $origin.restartCount }}
        started: false
        state:
          terminated:
            exitCode: 0
            finishedAt: {{ $now | Quote }}
            reason: Completed
            startedAt: {{ $now | Quote }}
      {{ end }}
      phase: Succeeded
