apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-init-container-create-failed
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
    - key: '.metadata.deletionTimestamp'
      operator: 'DoesNotExist'
    - key: '.status.phase'
      operator: 'In'
      values:
      - 'Pending'
    - key: '.status.initContainerStatuses.[].state.running.startedAt'
      operator: 'Exists'
  weight: 1
  delay:
    durationMilliseconds: 1000
    jitterDurationMilliseconds: 5000
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $root := . }}
      initContainerStatuses:
      {{ range $index, $item := .spec.initContainers }}
      {{ $origin := index $root.status.initContainerStatuses $index }}
      - image: {{ $item.image | Quote }}
        name: {{ $item.name | Quote }}
        ready: false
        {{/* TODO: Add incrementing restartCount. */}}
        restartCount: {{ len (printf "x%*s" $origin.restartCount.Int64 "x") }}
        started: false
        state:
          waiting:
            reason: ContainerCreating
      {{ end }}
