kind: Stage
apiVersion: kwok.x-k8s.io/v1alpha1
metadata:
  name: node-heartbeat
spec:
  resourceRef:
    apiGroup: v1
    kind: Node
  selector:
    matchExpressions:
    - key: '.status.phase'
      operator: 'In'
      values:
      - Running
    - key: '.status.conditions.[] | select( .type == "Ready" ) | .status'
      operator: 'In'
      values:
      - 'True'
  delay:
    durationMilliseconds: 20000
    jitterDurationMilliseconds: 25000
  next:
    statusTemplate: |
      {{ $now := Now }}
      {{ $lastTransitionTime := or .creationTimestamp $now }}
      conditions:
      {{ range NodeConditions }}
      - lastHeartbeatTime: {{ $now | Quote }}
        lastTransitionTime: {{ $lastTransitionTime | Quote }}
        message: {{ .message | Quote }}
        reason: {{ .reason | Quote }}
        status: {{ .status | Quote }}
        type: {{ .type | Quote }}
      {{ end }}
  immediateNextStage: true
