name: GolangCI Lint
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
    - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: "1.22"
    - uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.58.2
        args: --timeout=30m --config=.golangci.yaml
