name: Releases
on:
  push:
    tags:
      - v*

env:
  PUSH: 'true'
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  releases:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build binary for registry.k8s.io
        if: ${{ github.repository == 'kubernetes-sigs/kwok' }}
        env:
          GH_RELEASE: ${{ github.repository }}
          IMAGE_PREFIX: registry.k8s.io/kwok
          BINARY_PREFIX: https://github.com/${{ github.repository }}/releases/download
        run: |
          REF=${{ github.ref }}
          GIT_TAG="${REF##*/}" make cross-build
      - name: Build binary for ghcr.io
        if: ${{ github.repository != 'kubernetes-sigs/kwok' }}
        env:
          GH_RELEASE: ${{ github.repository }}
          IMAGE_PREFIX: ghcr.io/${{ github.repository }}
          BINARY_PREFIX: https://github.com/${{ github.repository }}/releases/download
        run: |
          REF=${{ github.ref }}
          GIT_TAG="${REF##*/}" make cross-build
      - name: Build kwok image
        env:
          IMAGE_PREFIX: ghcr.io/${{ github.repository }}
        run: |
          REF=${{ github.ref }}
          GIT_TAG="${REF##*/}" make cross-image
      - name: Build cluster image
        env:
          IMAGE_PREFIX: ghcr.io/${{ github.repository }}
        run: |
          REF=${{ github.ref }}
          GIT_TAG="${REF##*/}" make cross-cluster-image
